spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@springdb_medium?TNS_ADMIN=src/main/resources/Wallet_SpringDB
    username: admin
    password: Angelus_ps4$
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
  oracle:
    jdbc:
      fanEnabled: false
